[package]
name = "dns"
version = "0.1.0"
authors = ["DrPandemic <DrPandemic@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.16.1"
tokio = { version = "0.2", features = ["full"] }
reqwest = { version = "0.10", features = ["json"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "filter_vector_benchmark"
harness = false
